source 'https://rubygems.org'

gem 'rails', '~> 7.1'
gem 'pg', '>= 1.1'
gem 'puma', '~> 6.0'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.2'
gem 'devise', '~> 4.9'

group :development do
  gem 'rubocop', '~> 1.59'
end
